apiVersion: apps/v1
kind: Deployment
metadata:
  name: relatorios-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: relatorios-api
  template:
    metadata:
      labels:
        app: relatorios-api
    spec:
      containers:
      - name: relatorios-api
        image: relatorios-api
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: relatorios-api-service
spec:
  selector:
    app: relatorios-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  type: NodePort
